import "./globals.css";

export const metadata = {
  title: "Next.js Tutorials",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1><a herf="/read/1">WEB</a></h1>
        <ol>
          <li><a herf="/read/2">CSS</a></li>
        </ol>
        {children}
        <ul>
          <li><a herf="/create">Create</a></li>
          <li><a herf="/update/1">Update</a></li>
          <li><input type="button" value="delete" /></li>
        </ul>
        </body>
    </html>
  );
}
